list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_button/icon_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_layouts_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/dacligga_lvgl_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/dacligga_lvgl.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/big_shoulders_45_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/big_shoulders_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_earbuds_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_gear_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_midi_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_speaker_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_usb_data.c)